In [9]:
# #넘파이
# import numpy as np

# #랜덤 시드
# np.random.seed(2026)

# #예시: 소수점 3자리까지 출력하기
# np.set_printoptions(precision=3)
# arr = np.array([1.234567, 2.345678, 3.456789])
# print(arr)

# #리스트 활용
# data2 = [6,7.5,8,0,1]
# arr1=np.array(data2)
# arr1


arr = np.arange(20)
arr.reshape((5,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

arr_slice = arr[5:8]
arr_slice


[0 1 2 3 4 5 6 7 8 9]


array([5, 6, 7])

In [ ]:
#copy()매서드
arr_slice2=arr[5:8].copy()
arr_slice2


array([5, 6, 7])

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

arr2d[0]

array([1, 2, 3])

In [ ]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],

                  [[7, 8, 9],
                   [10, 11, 12]]])
arr3d

arr3d.shape

arr3d[0]


#기존 항목 기억해 두기
old_values=arr3d[0].copy()


SyntaxError: invalid syntax (2820261697.py, line 18)

In [ ]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
names



array(['Bob', 'Joe', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [46]:
import numpy as np

# 7x4 크기의 정규분포 난수 배열 생성
data = np.random.randn(7, 4)
print(data)

[[-0.432 -1.393  0.312 -0.013]
 [ 1.45   0.298 -0.83  -1.596]
 [ 0.613 -0.318 -0.074 -0.609]
 [-2.     0.908  0.483  0.222]
 [ 0.664 -1.246  1.969 -0.319]
 [ 0.36   0.746 -2.725  1.675]
 [ 0.056 -1.699 -0.361  2.73 ]]
